import prisma from "../lib/db";
import { buildGraph, percentile99 } from "../lib/graph-builder";
import { buildAccountGraphFeatures, type AccountGraphFeatures } from "../lib/account-graph-features";
import { trainGradientBoosting, predictGradientProbabilities } from "../lib/gradient-boosting-detector";

interface B { tx:number; inTx:number; outTx:number; received:number; sent:number; counterparties:Set<string>; formats:Set<string>; }
const empty=():B=>({tx:0,inTx:0,outTx:0,received:0,sent:0,counterparties:new Set(),formats:new Set()});
function behavior(ts:any[]){const m=new Map<string,B>();for(const t of ts){const a=m.get(t.fromAccountId)??empty(),b=m.get(t.toAccountId)??empty();a.tx++;a.outTx++;a.sent+=t.amountPaid;a.counterparties.add(t.toAccountId);a.formats.add(t.paymentFormat);b.tx++;b.inTx++;b.received+=t.amountReceived;b.counterparties.add(t.fromAccountId);b.formats.add(t.paymentFormat);m.set(t.fromAccountId,a);m.set(t.toAccountId,b);}return m;}
const fb:AccountGraphFeatures={inDegree:0,outDegree:0,totalDegree:0,communitySize:1,communityDensity:0,communityTriangleCount:0,inOutAmountRatio:0};
function vec(b:B,g:AccountGraphFeatures){return[Math.log1p(b.tx),Math.log1p(b.inTx),Math.log1p(b.outTx),Math.log1p(b.received),Math.log1p(b.sent),Math.log1p(b.counterparties.size),Math.log1p(b.formats.size),Math.log1p(g.inDegree),Math.log1p(g.outDegree),Math.log1p(g.totalDegree),Math.log1p(g.communitySize),g.communityDensity,Math.log1p(g.communityTriangleCount),g.inOutAmountRatio];}
function sample(rows:any[],negatives:number){const p=rows.filter(x=>x.label===1),n=rows.filter(x=>x.label===0);const stride=Math.max(1,Math.ceil(n.length/negatives));return[...p,...n.filter((_:any,i:number)=>i%stride===0).slice(0,negatives)];}
function f1(probs:number[],labels:number[],threshold:number){let tp=0,fp=0,fn=0;for(let i=0;i<labels.length;i++){const y=probs[i]>=threshold;if(y&&labels[i])tp++;else if(y&&!labels[i])fp++;else if(!y&&labels[i])fn++;}const p=tp+fp?tp/(tp+fp):0,r=tp+fn?tp/(tp+fn):0;return p+r?2*p*r/(p+r):0;}
function bestThreshold(p:number[],y:number[]){let best={threshold:.5,f1:-1};for(let i=1;i<=99;i++){const t=i/100,v=f1(p,y,t);if(v>best.f1)best={threshold:t,f1:v};}return best;}
async function main(){console.log("══════════════════════════════════════════");console.log(" RingWatch — Stage 8: Validation-Based GB");console.log("══════════════════════════════════════════\n");const select={fromAccountId:true,toAccountId:true,amountPaid:true,amountReceived:true,timestamp:true,paymentFormat:true,isLaunderingLabel:true} as const;const train=await prisma.transaction.findMany({where:{split:"TRAIN"},select});const test=await prisma.transaction.findMany({where:{split:"TEST"},select});
const cut=Math.floor(train.length*.8);const fit=train.slice(0,cut),val=train.slice(cut);console.log(` TRAIN fit: ${fit.length.toLocaleString()}`);console.log(` TRAIN validation: ${val.length.toLocaleString()}`);console.log(` TEST holdout: ${test.length.toLocaleString()}`);
const gd=buildGraph(fit,percentile99(fit.map(t=>t.amountPaid)));const gf=buildAccountGraphFeatures(fit,gd.communities);const labels=(ts:any[])=>{const s=new Set<string>();for(const t of ts)if(t.isLaunderingLabel){s.add(t.fromAccountId);s.add(t.toAccountId);}return s;};const fitLab=labels(fit),valLab=labels(val),testLab=labels(test);const fitB=behavior(fit),valB=behavior(val),testB=behavior(test);
const rows=(b:Map<string,B>,labs:Set<string>)=>Array.from(b.entries()).map(([id,x])=>({features:vec(x,gf.get(id)??fb),label:labs.has(id)?1:0}));const fitRows=sample(rows(fitB,fitLab),5000);const valRows=rows(valB,valLab);console.log(` Training sample: ${fitRows.length.toLocaleString()} (${fitRows.filter(x=>x.label).length} positive)`);const model=trainGradientBoosting(fitRows.map(x=>x.features),fitRows.map(x=>x.label),{nEstimators:80,learningRate:.04,maxDepth:3,subsample:.8,maxFeatures:"sqrt",randomState:42});const vp=predictGradientProbabilities(model,valRows.map(x=>x.features));const chosen=bestThreshold(vp,valRows.map(x=>x.label));console.log(` Selected threshold from TRAIN validation: ${chosen.threshold.toFixed(2)}`);console.log(` Validation F1: ${(chosen.f1*100).toFixed(2)}%`);
const testRows=rows(testB,testLab),tp=predictGradientProbabilities(model,testRows.map(x=>x.features));const t=f1(tp,testRows.map(x=>x.label),chosen.threshold);let TP=0,FP=0,FN=0,TN=0;for(let i=0;i<tp.length;i++){const y=tp[i]>=chosen.threshold;if(y&&testRows[i].label)TP++;else if(y)FP++;else if(testRows[i].label)FN++;else TN++;}const prec=TP+FP?TP/(TP+FP):0,rec=TP+FN?TP/(TP+FN):0;console.log("\n════════ TEST SET (HELD OUT) ════════");console.log(` TP: ${TP}`);console.log(` FP: ${FP}`);console.log(` FN: ${FN}`);console.log(` TN: ${TN}`);console.log(` Precision: ${(prec*100).toFixed(2)}%`);console.log(` Recall:    ${(rec*100).toFixed(2)}%`);console.log(` F1:        ${(t*100).toFixed(2)}%`);console.log("\nStage 8 complete: threshold selected on TRAIN validation only; TEST labels used only for final metrics.");await prisma.$disconnect();}
main().catch(e=>{console.error(e);prisma.$disconnect();process.exit(1);});
