import prisma from "../lib/db";
import { trainGradientBoosting, predictGradientProbabilities } from "../lib/gradient-boosting-detector";

interface B { tx:number; inTx:number; outTx:number; received:number; sent:number; counterparties:Set<string>; formats:Set<string>; }
const empty=():B=>({tx:0,inTx:0,outTx:0,received:0,sent:0,counterparties:new Set(),formats:new Set()});
function behavior(ts:any[]){const m=new Map<string,B>();for(const t of ts){const a=m.get(t.fromAccountId)??empty(),b=m.get(t.toAccountId)??empty();a.tx++;a.outTx++;a.sent+=t.amountPaid;a.counterparties.add(t.toAccountId);a.formats.add(t.paymentFormat);b.tx++;b.inTx++;b.received+=t.amountReceived;b.counterparties.add(t.fromAccountId);b.formats.add(t.paymentFormat);m.set(t.fromAccountId,a);m.set(t.toAccountId,b);}return m;}
function labelSet(ts:any[]){const s=new Set<string>();for(const t of ts)if(t.isLaunderingLabel){s.add(t.fromAccountId);s.add(t.toAccountId);}return s;}
function vec(b:B){return[Math.log1p(b.tx),Math.log1p(b.inTx),Math.log1p(b.outTx),Math.log1p(b.received),Math.log1p(b.sent),Math.log1p(b.counterparties.size),Math.log1p(b.formats.size)];}
function rows(b:Map<string,B>,labels:Set<string>){return Array.from(b.entries()).map(([id,x])=>({features:vec(x),label:labels.has(id)?1:0}));}
function sample(rows:any[],negatives:number){const p=rows.filter(x=>x.label===1),n=rows.filter(x=>x.label===0);const stride=Math.max(1,Math.ceil(n.length/negatives));return[...p,...n.filter((_:any,i:number)=>i%stride===0).slice(0,negatives)];}
function score(probs:number[],labels:number[],threshold:number){let tp=0,fp=0,fn=0,tn=0;for(let i=0;i<labels.length;i++){const y=probs[i]>=threshold;if(y&&labels[i])tp++;else if(y)fp++;else if(labels[i])fn++;else tn++;}const p=tp+fp?tp/(tp+fp):0,r=tp+fn?tp/(tp+fn):0,f=p+r?2*p*r/(p+r):0;return{tp,fp,fn,tn,p,r,f};}
function choose(probs:number[],labels:number[]){let best={threshold:.5,f:-1};for(let i=1;i<=99;i++){const t=i/100,r=score(probs,labels,t);if(r.f>best.f)best={threshold:t,f:r.f};}return best;}
async function load(where:any,attempt=1):Promise<any[]>{try{return await prisma.transaction.findMany({where,select:{fromAccountId:true,toAccountId:true,amountPaid:true,amountReceived:true,paymentFormat:true,isLaunderingLabel:true}});}catch(e){if(attempt>=5)throw e;const wait=1000*attempt;console.log(`Database connection failed; retrying in ${wait}ms (${attempt}/5)`);await new Promise(r=>setTimeout(r,wait));return load(where,attempt+1);}}
async function main(){console.log("══════════════════════════════════════════");console.log(" RingWatch — Stage 9: Final Behavioral Gradient Boosting");console.log("══════════════════════════════════════════\n");console.log("Loading data (automatic DB retry enabled)...");const train=await load({split:"TRAIN"});const test=await load({split:"TEST"});console.log(` TRAIN transactions: ${train.length.toLocaleString()}`);console.log(` TEST transactions:  ${test.length.toLocaleString()}`);
const cut=Math.floor(train.length*.8),fit=train.slice(0,cut),val=train.slice(cut);const fitRows=rows(behavior(fit),labelSet(fit));const valRows=rows(behavior(val),labelSet(val));const testRows=rows(behavior(test),labelSet(test));const sampled=sample(fitRows,5000);console.log(` TRAIN fit accounts: ${fitRows.length.toLocaleString()}`);console.log(` TRAIN validation accounts: ${valRows.length.toLocaleString()}`);console.log(` Training sample: ${sampled.length.toLocaleString()} (${sampled.filter(x=>x.label).length} positive, ${sampled.filter(x=>!x.label).length} negative)`);
const model=trainGradientBoosting(sampled.map(x=>x.features),sampled.map(x=>x.label),{nEstimators:120,learningRate:.03,maxDepth:2,subsample:.8,maxFeatures:"sqrt",randomState:42});const vp=predictGradientProbabilities(model,valRows.map(x=>x.features));const chosen=choose(vp,valRows.map(x=>x.label));console.log(` Selected threshold from TRAIN validation: ${chosen.threshold.toFixed(2)}`);console.log(` Validation F1: ${(chosen.f*100).toFixed(2)}%`);
const tp=predictGradientProbabilities(model,testRows.map(x=>x.features));const r=score(tp,testRows.map(x=>x.label),chosen.threshold);console.log("\n════════ TEST SET (HELD OUT) ════════");console.log(` TP: ${r.tp}`);console.log(` FP: ${r.fp}`);console.log(` FN: ${r.fn}`);console.log(` TN: ${r.tn}`);console.log(` Precision: ${(r.p*100).toFixed(2)}%`);console.log(` Recall:    ${(r.r*100).toFixed(2)}%`);console.log(` F1:        ${(r.f*100).toFixed(2)}%`);console.log("\nStage 9 complete. TEST labels were used only for final metrics; threshold was selected on TRAIN validation.");await prisma.$disconnect();}
main().catch(e=>{console.error(e);prisma.$disconnect();process.exit(1);});
