import prisma from "../lib/db";
import { trainGradientBoosting, predictGradientProbabilities } from "../lib/gradient-boosting-detector";

type Tx = { fromAccountId:string; toAccountId:string; amountPaid:number; amountReceived:number; timestamp:Date; paymentFormat:string; isLaunderingLabel:boolean };
type Stats = { sentN:number; recvN:number; sentAmt:number; recvAmt:number; sentCp:Set<string>; recvCp:Set<string> };
const empty=():Stats=>({sentN:0,recvN:0,sentAmt:0,recvAmt:0,sentCp:new Set(),recvCp:new Set()});
function buildStats(ts:Tx[]){const m=new Map<string,Stats>();for(const t of ts){const a=m.get(t.fromAccountId)??empty(),b=m.get(t.toAccountId)??empty();a.sentN++;a.sentAmt+=t.amountPaid;a.sentCp.add(t.toAccountId);b.recvN++;b.recvAmt+=t.amountReceived;b.recvCp.add(t.fromAccountId);m.set(t.fromAccountId,a);m.set(t.toAccountId,b);}return m;}
function ratio(a:number,b:number){return Math.log1p(Math.max(0,a))/(Math.log1p(Math.max(0,b))+1e-9);}
function features(t:Tx,s:Map<string,Stats>,formats:Map<string,number>){const a=s.get(t.fromAccountId)??empty(),b=s.get(t.toAccountId)??empty(),hour=t.timestamp.getUTCHours(),dow=t.timestamp.getUTCDay(),fmt=formats.get(t.paymentFormat)??0;return[Math.log1p(t.amountPaid),Math.log1p(t.amountReceived),Math.log1p(Math.abs(t.amountPaid-t.amountReceived)),ratio(t.amountPaid,t.amountReceived),Math.log1p(a.sentN),Math.log1p(a.recvN),Math.log1p(a.sentAmt),Math.log1p(a.recvAmt),Math.log1p(a.sentCp.size),Math.log1p(a.recvCp.size),Math.log1p(b.sentN),Math.log1p(b.recvN),Math.log1p(b.sentAmt),Math.log1p(b.recvAmt),Math.log1p(b.sentCp.size),Math.log1p(b.recvCp.size),Math.sin(2*Math.PI*hour/24),Math.cos(2*Math.PI*hour/24),Math.sin(2*Math.PI*dow/7),Math.cos(2*Math.PI*dow/7),fmt];}
function sample(rows:{x:number[];y:number}[],negPerPos:number){const p=rows.filter(r=>r.y),n=rows.filter(r=>!r.y);const limit=Math.min(n.length,p.length*negPerPos),stride=Math.max(1,Math.floor(n.length/limit));const chosen=n.filter((_,i)=>i%stride===0).slice(0,limit);return[...p,...chosen];}
function metrics(p:number[],y:number[],t:number){let tp=0,fp=0,fn=0,tn=0;for(let i=0;i<y.length;i++){const z=p[i]>=t;if(z&&y[i])tp++;else if(z)fp++;else if(y[i])fn++;else tn++;}const pr=tp+fp?tp/(tp+fp):0,re=tp+fn?tp/(tp+fn):0,f=pr+re?2*pr*re/(pr+re):0;return{tp,fp,fn,tn,precision:pr,recall:re,f1:f};}
function bestThreshold(p:number[],y:number[]){let best={threshold:.5,f1:-1};for(let i=1;i<100;i++){const r=metrics(p,y,i/100);if(r.f1>best.f1)best={threshold:i/100,f1:r.f1};}return best;}
async function main(){console.log("══════════════════════════════════════════");console.log(" RingWatch — Stage 10: Transaction-Level Gradient Boosting");console.log("══════════════════════════════════════════\n");const select={fromAccountId:true,toAccountId:true,amountPaid:true,amountReceived:true,timestamp:true,paymentFormat:true,isLaunderingLabel:true} as const;const train=await prisma.transaction.findMany({where:{split:"TRAIN"},orderBy:{timestamp:"asc"},select});const test=await prisma.transaction.findMany({where:{split:"TEST"},orderBy:{timestamp:"asc"},select});console.log(` TRAIN transactions: ${train.length.toLocaleString()}`);console.log(` TEST transactions:  ${test.length.toLocaleString()}`);const cut=Math.floor(train.length*.8),fit=train.slice(0,cut),val=train.slice(cut);const stats=buildStats(fit);const formats=new Map<string,number>();for(const t of fit)if(!formats.has(t.paymentFormat))formats.set(t.paymentFormat,formats.size);const make=(ts:Tx[])=>ts.map(t=>({x:features(t,stats,formats),y:t.isLaunderingLabel?1:0}));const fitRows=sample(make(fit),20),valRows=make(val),testRows=make(test);console.log(` FIT positives: ${fitRows.filter(r=>r.y).length.toLocaleString()}`);console.log(` FIT negatives: ${fitRows.filter(r=>!r.y).length.toLocaleString()}`);console.log(` VALIDATION positives: ${valRows.filter(r=>r.y).length.toLocaleString()}`);console.log(` TEST positives: ${testRows.filter(r=>r.y).length.toLocaleString()}`);console.log("\nTraining transaction-level gradient boosting...");const model=trainGradientBoosting(fitRows.map(r=>r.x),fitRows.map(r=>r.y),{nEstimators:120,learningRate:.035,maxDepth:4,subsample:.85,maxFeatures:"sqrt",randomState:42});const vp=predictGradientProbabilities(model,valRows.map(r=>r.x)),chosen=bestThreshold(vp,valRows.map(r=>r.y));console.log(` Selected threshold from TRAIN validation: ${chosen.threshold.toFixed(2)}`);console.log(` Validation F1: ${(chosen.f1*100).toFixed(2)}%`);const tp=predictGradientProbabilities(model,testRows.map(r=>r.x)),r=metrics(tp,testRows.map(x=>x.y),chosen.threshold);console.log("\n════════ TEST SET (HELD OUT) ════════");console.log(` TP: ${r.tp}`);console.log(` FP: ${r.fp}`);console.log(` FN: ${r.fn}`);console.log(` TN: ${r.tn}`);console.log(` Precision: ${(r.precision*100).toFixed(2)}%`);console.log(` Recall:    ${(r.recall*100).toFixed(2)}%`);console.log(` F1:        ${(r.f1*100).toFixed(2)}%`);console.log("\nStage 10 complete: transaction labels are used only for training/validation; TEST labels are used only for final metrics.");await prisma.$disconnect();}
main().catch(e=>{console.error(e);prisma.$disconnect();process.exit(1);});
